#.github/workflows/main.yml
name: Scratch org for review
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate DevHub
      run: |
        echo "${JWT_KEY_FILE}" > ./server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY }} --jwtkeyfile ./server.key --username ${{ secrets.HUB_USERNAME}} --setdefaultdevhubusername -a devhub
      env:
        JWT_KEY_FILE: ${{ secrets.JWT_KEY_FILE }}
      
    - name: Define Scratch org
      run: node_modules/sfdx-cli/bin/run force:org:create -v ${{ secrets.HUB_USERNAME}} -s -f config/project-scratch-def.json -a WFLogging-Scratch-Org -d 1

    - name: Deploy source to Scratch
      run: node_modules/sfdx-cli/bin/run force:source:push -u WFLogging-Scratch-Org

    - name: Run Apex test
      run: node_modules/sfdx-cli/bin/run force:apex:test:run -c -r human