#.github/workflows/main.yml
name: Scratch org for review
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
	
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
			
    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate DevHub
      run: |
        echo "${JWT_KEY_FILE}" > ./server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY }} --jwtkeyfile ./server.key --username ${{ secrets.HUB_USERNAME}} --setdefaultdevhubusername -a devhub
      env:
        JWT_KEY_FILE: ${{ secrets.JWT_KEY_FILE }}
      
    - name: Define Scratch org (CI)
- uses: sfdx-actions/setup-sfdx@v1
      run: node_modules/sfdx-cli/bin/run force:org:create -v devhub -s -f config/project-scratch-def.json -a ciorg -d 1

    - name: Deploy source
      run: node_modules/sfdx-cli/bin/run force:source:push -u ciorg

    - name: Run Apex test
      run: node_modules/sfdx-cli/bin/run force:apex:test:run -c -r human
